export const LANG = "ru-RU";

export const ru = {
  dateIs: "Дата равна",
  dateIsNot: "Дата не равна",
  dateBefore: "Дата до",
  dateAfter: "Дата после",
  dayNames: [
    "Воскресенье",
    "Понедельник",
    "Вторник",
    "Среда",
    "Четверг",
    "Пятница",
    "Суббота",
  ],
  dayNamesShort: ["Вск", "Пнд", "Втр", "Срд", "Чтв", "Птн", "Сбт"],
  dayNamesMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
  monthNames: [
    "Январь",
    "Февраль",
    "Март",
    "Апрель",
    "Май",
    "Июнь",
    "Июль",
    "Август",
    "Сентябрь",
    "Октябрь",
    "Ноябрь",
    "Декабрь",
  ],
  monthNamesShort: [
    "Янв",
    "Фев",
    "Мар",
    "Апр",
    "Май",
    "Июн",
    "Июл",
    "Авг",
    "Сен",
    "Окт",
    "Ноя",
    "Дек",
  ],
  chooseYear: "Выбрать год",
  chooseMonth: "Выбрать месяц",
  chooseDate: "Выбрать дату",
  prevDecade: "Предыдущее десятилетие",
  nextDecade: "Следующее десятилетие",
  prevYear: "Предыдущий год",
  nextYear: "Следующий год",
  prevMonth: "Предыдущий месяц",
  nextMonth: "Следующий месяц",
  prevHour: "Предыдущий час",
  nextHour: "Следующий час",
  prevMinute: "Предыдущая минута",
  nextMinute: "Следующая минута",
  prevSecond: "Предыдущая секунда",
  nextSecond: "Следующая секунда",
  am: "до полудня",
  pm: "после полудня",
  today: "Сегодня",
  weekHeader: "Нед.",
  firstDayOfWeek: 1,
  showMonthAfterYear: false,
  dateFormat: "dd.mm.yyyy",
};
